### ISSUE TITLE
Add a Readme File

### ISSUE THREAD

**Issue by Smarshal21** [iiitl/Binary#1]

**Comment by Akshit-Nandan** [comment]
Do we need to create a new readme file or edit the existing one ?

**Comment by Smarshal21** [comment]
Create a new readme file

**Comment by Smarshal21** [comment]
Edit the existing file

**Comment by Akshit-Nandan** [comment]
Sir I want to work on this .
So can you assign it to me.

**Comment by Smarshal21** [comment]
assigned
